[versions]
kotlin = "1.9.20"
okio = "3.7.0"
jewel = "0.13.2"
compose-desktop = "1.6.0-dev1369"

[libraries]
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
jewel-standalone = { module = "org.jetbrains.jewel:jewel-int-ui-standalone", version.ref = "jewel" }
jewel-deco-win = { group = "org.jetbrains.jewel", name = "jewel-int-ui-decorated-window", version.ref = "jewel" }

[plugins]
compose-desktop = { id = "org.jetbrains.compose", version.ref = "compose-desktop" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
