[versions]
kotlin = "1.9.20"
okio = "3.7.0"

[libraries]
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]